// Copyright © 2026 Joe Pruskowski. All rights reserved.
/**
 * Section 9 of QA_Phase_3.4 — Tournament Seed Bots.
 *
 * Covers, API-only (no UI):
 *   9a. Add seed bots to a recurring tournament
 *   9b. Seed-bot propagation to the next recurring occurrence
 *   9c. Seed bots play BOT_VS_BOT games to completion
 *   9d. Remove a seed bot
 *   9e. Skill-level → botModelId mapping for all four levels
 *
 * Not covered here:
 *   9f — scheduler unit tests run via vitest, outside the e2e stack.
 *
 * All tournaments are created with `isTest: true` so they don't pollute the
 * public /tournaments page.
 */

import { test, expect, request as playwrightRequest } from '@playwright/test'
import { signIn, fetchAuthToken, tournamentApi } from './helpers.js'

const LANDING_URL = process.env.LANDING_URL  || 'http://localhost:5174'
const BACKEND_URL = process.env.BACKEND_URL  || 'http://localhost:3000'

const haveAdmin = !!process.env.TEST_ADMIN_EMAIL && !!process.env.TEST_ADMIN_PASSWORD
const haveUser  = !!process.env.TEST_USER_EMAIL  && !!process.env.TEST_USER_PASSWORD

// Skill levels expected to map to specific botModelId suffixes, per QA 9e.
const SKILL_MAP = [
  { label: 'rusty',    expected: 'novice'       },
  { label: 'copper',   expected: 'intermediate' },
  { label: 'sterling', expected: 'advanced'     },
  { label: 'magnus',   expected: 'master'       },
]

test.describe('Tournament seed bots — QA Section 9', () => {
  test.setTimeout(90_000)

  // ── 9a + 9e: add seed bots, verify list + config + skill mapping ──────────
  test('9a/9e: add seed bots across all skill levels — list + participants + botModelId map', async () => {
    test.skip(!haveAdmin, 'Set TEST_ADMIN_EMAIL + TEST_ADMIN_PASSWORD')

    const adminCtx = await playwrightRequest.newContext({ baseURL: LANDING_URL })
    try {
      const adminPageLike = { context: () => ({ request: adminCtx }) }
      await signIn(adminPageLike, process.env.TEST_ADMIN_EMAIL, process.env.TEST_ADMIN_PASSWORD, LANDING_URL)
      const token = await fetchAuthToken(adminCtx, LANDING_URL)
      const api = tournamentApi(LANDING_URL)

      const uniq = `seed-${Date.now()}`
      const tournament = await api.create({ request: adminCtx, token }, {
        name:         `E2E Seed ${uniq}`,
        description:  `Seed-bots e2e (${uniq})`,
        game:         'xo',
        mode:         'BOT_VS_BOT',
        format:       'PLANNED',
        bracketType:  'SINGLE_ELIM',
        bestOfN:      1,
        minParticipants: 2,
        maxParticipants: 8,
        startMode:    'MANUAL',
        isRecurring:  true,
        recurrenceInterval: 'WEEKLY',
        isTest:       true,
      })

      try {
        await api.publish({ request: adminCtx, token }, tournament.id)

        // Add one seed bot per skill level — distinct names ensure unique usernames.
        const bots = SKILL_MAP.map(({ label }, i) => ({
          name:       `SeedBot-${uniq}-${label}-${i}`,
          skillLevel: label,
        }))
        const { added } = await api.addSeedBots({ request: adminCtx, token }, tournament.id, bots)
        expect(added).toHaveLength(SKILL_MAP.length)

        // 9e: each returned row's botModelId matches `seed:<username>:<skill>`
        // where <skill> is the mapped suffix (rusty → novice, etc.). The
        // username portion is generated by makeSeedBotUsername() and may
        // include any mix of alphanumerics and hyphens — we only assert the
        // prefix and skill suffix here.
        for (let i = 0; i < SKILL_MAP.length; i++) {
          const { expected } = SKILL_MAP[i]
          const row = added[i]
          expect(row.skillLevel).toBe(expected)
          expect(row.botModelId).toMatch(new RegExp(`^seed:[a-z0-9-]+:${expected}$`))
        }

        // 9a: list endpoint reports the same 4 bots.
        const seedList = await api.listSeedBots({ request: adminCtx, token }, tournament.id)
        expect(seedList).toHaveLength(SKILL_MAP.length)
        const listedIds = new Set(seedList.map(b => b.userId))
        for (const b of added) expect(listedIds.has(b.userId)).toBe(true)

        // 9a: the tournament's participants list now includes all 4 bots.
        const tDetail = await api.get({ request: adminCtx, token }, tournament.id)
        const participantUserIds = new Set((tDetail.participants ?? []).map(p => p.userId))
        for (const b of added) expect(participantUserIds.has(b.userId)).toBe(true)
      } finally {
        await api.cancel({ request: adminCtx, token }, tournament.id).catch(() => {})
      }
    } finally {
      await adminCtx.dispose()
    }
  })

  // ── 9d: remove a seed bot — config gone + participant WITHDRAWN ──────────
  test('9d: remove seed bot withdraws participant and clears config', async () => {
    test.skip(!haveAdmin, 'Set TEST_ADMIN_EMAIL + TEST_ADMIN_PASSWORD')

    const adminCtx = await playwrightRequest.newContext({ baseURL: LANDING_URL })
    try {
      const adminPageLike = { context: () => ({ request: adminCtx }) }
      await signIn(adminPageLike, process.env.TEST_ADMIN_EMAIL, process.env.TEST_ADMIN_PASSWORD, LANDING_URL)
      const token = await fetchAuthToken(adminCtx, LANDING_URL)
      const api = tournamentApi(LANDING_URL)

      const uniq = `seed-remove-${Date.now()}`
      const tournament = await api.create({ request: adminCtx, token }, {
        name: `E2E Seed Remove ${uniq}`, description: `9d (${uniq})`,
        game: 'xo', mode: 'BOT_VS_BOT', format: 'PLANNED', bracketType: 'SINGLE_ELIM',
        bestOfN: 1, minParticipants: 2, maxParticipants: 4,
        startMode: 'MANUAL', isRecurring: true, recurrenceInterval: 'WEEKLY',
        isTest: true,
      })

      try {
        await api.publish({ request: adminCtx, token }, tournament.id)
        const { added } = await api.addSeedBots({ request: adminCtx, token }, tournament.id, [
          { name: `Keep-${uniq}`,   skillLevel: 'rusty'  },
          { name: `Remove-${uniq}`, skillLevel: 'copper' },
        ])
        const victim = added.find(b => b.displayName.startsWith('Remove-'))
        expect(victim).toBeDefined()

        const status = await api.removeSeedBot({ request: adminCtx, token }, tournament.id, victim.userId)
        expect(status).toBe(204)

        // Config row removed
        const seedList = await api.listSeedBots({ request: adminCtx, token }, tournament.id)
        expect(seedList.map(b => b.userId)).not.toContain(victim.userId)
        expect(seedList).toHaveLength(1)

        // Participant marked WITHDRAWN (not deleted — audit trail)
        const tDetail = await api.get({ request: adminCtx, token }, tournament.id)
        const vicParticipant = (tDetail.participants ?? []).find(p => p.userId === victim.userId)
        expect(vicParticipant).toBeDefined()
        expect(vicParticipant.status).toBe('WITHDRAWN')
      } finally {
        await api.cancel({ request: adminCtx, token }, tournament.id).catch(() => {})
      }
    } finally {
      await adminCtx.dispose()
    }
  })

  // ── 9b: seed bots propagate to the next recurring occurrence ─────────────
  // Flow: create a recurring template with a startTime in the past, add a
  // seed bot, force-complete the template, trigger the recurring sweep, and
  // verify a fresh occurrence was created that also carries the seed bot
  // (both as a TournamentParticipant and as a TournamentSeedBot config row
  // on the new occurrence). Relies on the admin force-complete + sweep
  // endpoints added to the service.
  test('9b: seed bots propagate to the next recurring occurrence', async () => {
    test.skip(!haveAdmin, 'Set TEST_ADMIN_EMAIL + TEST_ADMIN_PASSWORD')

    const adminCtx = await playwrightRequest.newContext({ baseURL: LANDING_URL })
    try {
      const adminPageLike = { context: () => ({ request: adminCtx }) }
      await signIn(adminPageLike, process.env.TEST_ADMIN_EMAIL, process.env.TEST_ADMIN_PASSWORD, LANDING_URL)
      const token = await fetchAuthToken(adminCtx, LANDING_URL)
      const api = tournamentApi(LANDING_URL)

      const uniq = `seed-propagate-${Date.now()}`
      // startTime in the past so `_nextOccurrenceStart` immediately returns
      // a future one (we want the sweep to spawn — not be skipped for lack
      // of a next start time).
      const pastStart = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
      const template = await api.create({ request: adminCtx, token }, {
        name: `E2E Seed Propagate ${uniq}`, description: `9b (${uniq})`,
        game: 'xo', mode: 'BOT_VS_BOT', format: 'PLANNED', bracketType: 'SINGLE_ELIM',
        bestOfN: 1, minParticipants: 2, maxParticipants: 4,
        startMode: 'MANUAL', startTime: pastStart,
        isRecurring: true, recurrenceInterval: 'DAILY',
        isTest: true,
      })

      try {
        await api.publish({ request: adminCtx, token }, template.id)
        const { added } = await api.addSeedBots({ request: adminCtx, token }, template.id, [
          { name: `Propagate-${uniq}`, skillLevel: 'rusty' },
        ])
        const seedBotUserId = added[0].userId

        // Force-complete the template so the sweep sees it as eligible for
        // the next occurrence. (Real templates reach COMPLETED through the
        // match-completion flow, which is out of scope for this test.)
        await api.forceComplete({ request: adminCtx, token }, template.id)

        // Fire the sweep.
        const summary = await api.triggerRecurringCheck({ request: adminCtx, token })
        expect(summary.templatesChecked).toBeGreaterThanOrEqual(1)
        expect(summary.occurrencesCreated).toBeGreaterThanOrEqual(1)

        // Find the new occurrence — same name, isRecurring=false, startTime > now.
        // `isTest: true` is inherited from the template so it won't pollute the
        // public list. We query with includeTest so our admin test can find it.
        const list = await api.list
          ? null  // placeholder; admin list uses the landing-proxied endpoint directly
          : null
        // Use the raw API client to list with includeTest
        const listRes = await adminCtx.get('/api/tournaments?includeTest=true', {
          headers: { Authorization: `Bearer ${token}` },
        })
        expect(listRes.ok()).toBe(true)
        const { tournaments } = await listRes.json()
        const occurrence = tournaments.find(t =>
          t.name === template.name && t.id !== template.id && t.isTest === true,
        )
        expect(occurrence, 'new occurrence was created').toBeDefined()
        expect(occurrence.status).toBe('REGISTRATION_OPEN')

        // Seed bot appears as a participant on the new occurrence.
        const occDetail = await api.get({ request: adminCtx, token }, occurrence.id)
        const occParticipantIds = new Set((occDetail.participants ?? []).map(p => p.userId))
        expect(occParticipantIds.has(seedBotUserId)).toBe(true)

        // Seed-bot config row propagated to the new occurrence too.
        const newOccSeedBots = await api.listSeedBots({ request: adminCtx, token }, occurrence.id)
        expect(newOccSeedBots.map(b => b.userId)).toContain(seedBotUserId)

        // Clean up the spawned occurrence too.
        await api.cancel({ request: adminCtx, token }, occurrence.id).catch(() => {})
      } finally {
        await api.cancel({ request: adminCtx, token }, template.id).catch(() => {})
      }
    } finally {
      await adminCtx.dispose()
    }
  })

  // ── 9c: BOT_VS_BOT with seed bots completes via admin-complete shortcut ───
  // The full run goes through botGameRunner which plays actual minimax games
  // at ~1.5s/move — too slow for CI. We verify the tournament *can* progress
  // to a match by publishing, adding seeds, starting, and admin-completing
  // the round-1 match. Real bot-runner behaviour is covered by the unit
  // tests referenced in 9f.
  test('9c: BOT_VS_BOT tournament with seed bots produces round-1 match that can complete', async () => {
    test.skip(!haveAdmin, 'Set TEST_ADMIN_EMAIL + TEST_ADMIN_PASSWORD')

    const adminCtx = await playwrightRequest.newContext({ baseURL: LANDING_URL })
    try {
      const adminPageLike = { context: () => ({ request: adminCtx }) }
      await signIn(adminPageLike, process.env.TEST_ADMIN_EMAIL, process.env.TEST_ADMIN_PASSWORD, LANDING_URL)
      const token = await fetchAuthToken(adminCtx, LANDING_URL)
      const api = tournamentApi(LANDING_URL)

      const uniq = `seed-bvb-${Date.now()}`
      const tournament = await api.create({ request: adminCtx, token }, {
        name: `E2E Seed BvB ${uniq}`, description: `9c (${uniq})`,
        game: 'xo', mode: 'BOT_VS_BOT', format: 'PLANNED', bracketType: 'SINGLE_ELIM',
        bestOfN: 1, minParticipants: 2, maxParticipants: 2,
        startMode: 'MANUAL', isTest: true,
      })

      try {
        await api.publish({ request: adminCtx, token }, tournament.id)
        const { added } = await api.addSeedBots({ request: adminCtx, token }, tournament.id, [
          { name: `BvB-A-${uniq}`, skillLevel: 'rusty'  },
          { name: `BvB-B-${uniq}`, skillLevel: 'copper' },
        ])
        expect(added).toHaveLength(2)

        await api.start({ request: adminCtx, token }, tournament.id)

        // Round-1 match should be created synchronously on start(). Poll for
        // it with a short budget so we don't depend on bot-runner timing.
        let match = null
        for (let i = 0; i < 20 && !match; i++) {
          const t = await api.get({ request: adminCtx, token }, tournament.id)
          const rounds = t.rounds ?? []
          for (const r of rounds) {
            for (const m of (r.matches ?? [])) {
              if (m.status === 'PENDING' || m.status === 'IN_PROGRESS') { match = m; break }
              if (m.status === 'COMPLETED') { match = m; break }  // botRunner already raced ahead
            }
            if (match) break
          }
          if (!match) await new Promise(r => setTimeout(r, 500))
        }
        expect(match, 'round-1 match was created').not.toBeNull()

        // If the bot runner hasn't already completed it, admin-complete so
        // the tournament can advance without hanging the suite.
        if (match.status !== 'COMPLETED') {
          await api.completeMatchAsAdmin({ request: adminCtx, token }, match.id, {
            winnerId: match.participant1Id,
            p1Wins:   1,
            p2Wins:   0,
            drawGames: 0,
          })
        }

        // With a 2-participant SINGLE_ELIM, the tournament is done after one
        // match. Poll until the top-level status reflects it.
        let finalStatus = null
        for (let i = 0; i < 20; i++) {
          const t = await api.get({ request: adminCtx, token }, tournament.id)
          if (t.status === 'COMPLETED') { finalStatus = t.status; break }
          await new Promise(r => setTimeout(r, 500))
        }
        expect(finalStatus).toBe('COMPLETED')
      } finally {
        await api.cancel({ request: adminCtx, token }, tournament.id).catch(() => {})
      }
    } finally {
      await adminCtx.dispose()
    }
  })
})
